# Generated by Django 4.2.10 on 2025-12-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(help_text='Primary normalized skill name (lowercase)', max_length=100, unique=True)),
                ('aliases', models.JSONField(blank=True, default=list, help_text='List of alternative names / synonyms')),
                ('category', models.CharField(blank=True, help_text='Skill category (AI, Backend, Cloud, etc.)', max_length=100)),
                ('source', models.CharField(default='manual', help_text='ESCO / O*NET / Manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['canonical_name'],
            },
        ),
    ]
