# Generated by Django 4.2.27 on 2026-01-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0004_chatsession_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
