# Generated by Django 4.2.27 on 2026-01-05 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0005_chatsession_resume_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsession',
            old_name='resume_text',
            new_name='document_text',
        ),
    ]
