# Generated by Django 4.2.27 on 2026-01-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matcher', '0006_rename_resume_text_chatsession_document_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
